### ISSUE TITLE
Error executing action `deploy` on resource 'deploy_revision[buildingdb]'

### ISSUE THREAD

**Issue by meetar** [polygon-city/chef-buildingdb#1]
When attempting to `vagrant up`

```
==> default: [2015-02-11T16:35:10+00:00] WARN: Error on deploying /srv/buildingdb/releases/8dbe12cbc5d54bff17f3f9192e32c5104a7463ae: undefined method `application' for Chef::Resource::DeployRevision
==> default: [2015-02-11T16:35:10+00:00] INFO: Removing failed deploy /srv/buildingdb/releases/8dbe12cbc5d54bff17f3f9192e32c5104a7463ae
==> default:
==> default: ================================================================================
==> default: Error executing action `deploy` on resource 'deploy_revision[buildingdb]'
==> default: ================================================================================
==> default:
==> default:
==> default: NoMethodError
==> default: -------------
==> default: undefined method `application' for Chef::Resource::DeployRevision
==> default:
==> default:
==> default: Cookbook Trace:
==> default: ---------------
==> default: /tmp/vagrant-chef/21bbe06df0de22bfaf81206de16d01a1/cookbooks/application_nodejs/providers/nodejs.rb:34:in `block (2 levels) in class_from_file'
==> default: /tmp/vagrant-chef/21bbe06df0de22bfaf81206de16d01a1/cookbooks/application/providers/default.rb:152:in `instance_eval'
==> default: /tmp/vagrant-chef/21bbe06df0de22bfaf81206de16d01a1/cookbooks/application/providers/default.rb:152:in `block (3 levels) in run_deploy'
==> default: /tmp/vagrant-chef/21bbe06df0de22bfaf81206de16d01a1/cookbooks/application/providers/default.rb:149:in `each'
==> default: /tmp/vagrant-chef/21bbe06df0de22bfaf81206de16d01a1/cookbooks/application/providers/default.rb:149:in `block (2 levels) in run_deploy'
==> default:
==> default:
==> default: Resource Declaration:
==> default: ---------------------
==> default: # In /tmp/vagrant-chef/21bbe06df0de22bfaf81206de16d01a1/cookbooks/application/providers/default.rb
==> default:
==> default: 130:   @deploy_resource = send(new_resource.strategy.to_sym, new_resource.name) do
==> default: 131:     action force ? :force_deploy : :deploy
==> default: 132:     scm_provider new_resource.scm_provider
==> default: 133:     revision new_resource.revision
==> default: 134:     repository new_resource.repository
==> default: 135:     enable_submodules new_resource.enable_submodules
==> default: 136:     user new_resource.owner
==> default: 137:     group new_resource.group
==> default: 138:     keep_releases new_resource.keep_releases
==> default: 139:     deploy_to new_resource.path
==> default: 140:     ssh_wrapper "#{new_resource.path}/deploy-ssh-wrapper" if new_resource.deploy_key
==> default: 141:     shallow_clone new_resource.shallow_clone
==> default: 142:     rollback_on_error new_resource.rollback_on_error
==> default: 143:     all_environments = ([new_resource.environment]+new_resource.sub_resources.map{|res| res.environment}).inject({}){|acc, val| acc.merge(val)}
==> default: 144:     environment all_environments
==> default: 145:     migrate new_resource.migrate
==> default: 146:     all_migration_commands = ([new_resource.migration_command]+new_resource.sub_resources.map{|res| res.migration_command}).select{|cmd| cmd && !cmd.empty?}
==> default: 147:     migration_command all_migration_commands.join(' && ')
==> default: 148:     restart_command do
==> default: 149:       ([new_resource]+new_resource.sub_resources).each do |res|
==> default: 150:         cmd = res.restart_command
==> default: 151:         if cmd.is_a? Proc
==> default: 152:           app_provider.deploy_provider.instance_eval(&cmd) # @see libraries/default.rb
==> default: 153:         elsif cmd && !cmd.empty?
==> default: 154:           execute cmd do
==> default: 155:             user new_resource.owner
==> default: 156:             group new_resource.group
==> default: 157:             environment all_environments
==> default: 158:           end
==> default: 159:         end
==> default: 160:       end
==> default: 161:     end
==> default: 162:     purge_before_symlink (new_resource.purge_before_symlink + new_resource.sub_resources.map(&:purge_before_symlink)).flatten
==> default:
==> default:
==> default:
==> default: Compiled Resource:
==> default: ------------------
==> default:
==> default: # Declared in /tmp/vagrant-chef/21bbe06df0de22bfaf81206de16d01a1/cookbooks/application/providers/default.rb:130:in `run_deploy'
==> default:
==> default: deploy_revision("buildingdb") do
==> default:   provider Chef::Provider::Deploy::Revision
==> default:   action [:deploy]
==> default:   updated true
==> default:   updated_by_last_action true
==> default:   retries 0
==> default:   retry_delay 2
==> default:   guard_interpreter :default
==> default:   deploy_to "/srv/buildingdb"
==> default:   environment {"NODE_ENV"=>"production"}
==> default:   repository_cache "cached-copy"
==> default:   symlinks {"config/config.js"=>"config/config.js", "config/setup.js"=>"config/setup.js", "tmp"=>"tmp"}
==> default:   revision "8dbe12cbc5d54bff17f3f9192e32c5104a7463ae"
==> default:   rollback_on_error true
==> default:   remote "origin"
==> default:   scm_provider Chef::Provider::Git
==> default:   keep_releases 5
==> default:   enable_checkout true
==> default:   checkout_branch "deploy"
==> default:   cookbook_name :buildingdb
==> default:   repo "https://github.com/polygon-city/building-database.git"
==> default:   user "www-data"
==> default:   group "www-data"
==> default:   restart_command #<Proc:0x000000073e8418@/tmp/vagrant-chef/21bbe06df0de22bfaf81206de16d01a1/cookbooks/application/providers/default.rb:148>
==> default:   before_migrate #<Proc:0x000000073ed710@/tmp/vagrant-chef/21bbe06df0de22bfaf81206de16d01a1/cookbooks/application/providers/default.rb:168>
==> default:   before_symlink #<Proc:0x000000073ed350@/tmp/vagrant-chef/21bbe06df0de22bfaf81206de16d01a1/cookbooks/application/providers/default.rb:171>
==> default:   before_restart #<Proc:0x000000073ecab8@/tmp/vagrant-chef/21bbe06df0de22bfaf81206de16d01a1/cookbooks/application/providers/default.rb:174>
==> default:   after_restart #<Proc:0x000000073ec798@/tmp/vagrant-chef/21bbe06df0de22bfaf81206de16d01a1/cookbooks/application/providers/default.rb:177>
==> default:   shared_path "/srv/buildingdb/shared"
==> default:   destination "/srv/buildingdb/shared/cached-copy"
==> default:   current_path "/srv/buildingdb/current"
==> default: end
==> default:
==> default:
==> default:
==> default: [2015-02-11T16:35:10+00:00] INFO: Running queued delayed notifications before re-raising exception
==> default: [2015-02-11T16:35:10+00:00] INFO: template[/etc/mongodb.conf] sending restart action to service[mongodb] (delayed)
==> default: [2015-02-11T16:35:10+00:00] INFO: service[mongodb] restarted
==> default: [2015-02-11T16:35:10+00:00] ERROR: Running exception handlers
==> default: [2015-02-11T16:35:10+00:00] ERROR: Exception handlers complete
==> default: [2015-02-11T16:35:10+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2015-02-11T16:35:10+00:00] ERROR: deploy_revision[buildingdb] (/tmp/vagrant-chef/21bbe06df0de22bfaf81206de16d01a1/cookbooks/application/providers/default.rb line 130) had an error: NoMethodError: undefined method `application' for Chef::Resource::DeployRevision
==> default: [2015-02-11T16:35:10+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

**Comment by meetar** [comment]
fixed by updating Ruby to 2.2.0, updating VirtualBox, and updating Vagrant to 1.7.2

**Comment by spifrancisv** [comment]
How did you update Ruby to 2.2.0? Is this the embedded Ruby that came with Vagrant 1.7.2 or not?

**Comment by meetar** [comment]
I believe I used the standard method of updating Ruby: http://stackoverflow.com/questions/17026441/how-to-install-a-specific-version-of-a-ruby-gem
And I'm not sure what version of Ruby came with Vagrant 1.7.2, but I as I recall it didn't work until I had updated them both separately.
